spring:
  application:
    name: esaka-eureka-service
server:
  address : 0.0.0.0
  port: 8070

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka
  instance:
    hostname: ${spring.application.name:esaka-eureka-service}
  server:
    wait-time-in-ms-when-sync-empty: 0