spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  application:
    name: esaka-auth

server:
  port: 8071

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8070}/eureka