spring:
  datasource:
    url: jdbc:postgresql://esaka-db-postgres:5432/${POSTGRESQL_DB}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  application:
    name: esaka-auth

security:
  token:
    secret: TheQuestionIsWhoCares
    maxAgeSeconds: 86400

server:
  port: 8072

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8070}/eureka