spring:
  application:
    name: esaka-gateway-api

server:
  port: 8079

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8070}/eureka
zuul:
  routes:
    esaka-filestore:
      path: /filestore/**
      serviceId: esaka-filestore
      stripPrefix: true
    esaka-auth:
      path: /auth/**
      serviceId: esaka-auth
      stripPrefix: true
      sensitive-headers: Cookie,Set-Cookie